services:
  # What to call the service hosting the site.
  php:
    # Use PHP 7.x with Apache to serve the WordPress site; this syntax pulls in the latest version of PHP 7
    image: tugboatqa/php:7-apache

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true
    commands:
      init:
        - apt-get update
        - apt-get install -y rsync

        - docker-php-ext-install opcache
        - docker-php-ext-install mysqli
        - a2enmod headers rewrite

        # Install wp-cli
        - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x wp-cli.phar
        - mv wp-cli.phar /usr/local/bin/wp
        - composer install --working-dir='wp-content/themes/starter_theme' --no-ansi

        # Link the document root to the expected path. This example links /web
        # to the docroot
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
